% Solve an Input-Output Fitting problem with a Neural Network
% Script generated by NFTOOL
%
% This script assumes these variables are defined:
%
%   houseInputs - input data.
%   houseTargets - target data.

clear all;
close all;

load house_dataset;
inputs = houseInputs;
targets = houseTargets;

A = importdata('data20131114_20.txt', '\t');
inputs = A(:, [1:3])';
targets = A(:, 4)';

A = importdata('data20131115_20.txt', '\t');
tstinputs = A(:, [1:3])';
tsttargets = A(:, 4)';

 
% Create a Fitting Network
hiddenLayerSize = 5;
net = fitnet(hiddenLayerSize);

% Set up Division of Data for Training, Validation, Testing
net.divideParam.trainRatio = 90/100;
net.divideParam.valRatio = 5/100;
net.divideParam.testRatio = 5/100;
 
% Train the Network
[net,tr] = train(net,inputs,targets);
 
% Test the Network
outputs = net(inputs);
errors = gsubtract(outputs,targets);
performance = perform(net,targets,outputs)
 
% View the Network
view(net)
 
% Plots
% Uncomment these lines to enable various plots.
%figure, plotperform(tr)
%figure, plottrainstate(tr)
%figure, plotfit(targets,outputs)
%figure, plotregression(targets,outputs)
%figure, ploterrhist(errors)

tInd = tr.testInd;
tstOutputs = net(tstinputs);
tstErrPercent = tstOutputs ./ tsttargets;
plot(tstErrPercent);
figure;
plot((1:size(tstOutputs, 2)), tstOutputs, 'ro');
hold on
plot((1:size(tsttargets, 2)), tsttargets, 'bx');

inputSettings = net.inputs{1}.processSettings{1, 2};
inputMin = inputSettings.xmin;
inputRange = inputSettigns.xrange;

outputSettings = net.inputs{1}.processSettings{1, 2};
outputMin = outputSettings.xmin;
outputRange = outputSettings.xrange;

IW = net.IW{1,1};
LW = net.LW{2,1};

b1 = net.b{1,1};
b2 = net.b{2,1};

filename = 'nnetmodel20';
fid = fopen(filename, 'w');

fprintf(fid, 'NUM_OF_NEURONS: %d\n\n', hiddenLayerSize);
fprintf(fid, 'Input_dimension: %d\n', size(inputMin, 1));
fprintf(fid, 'Output_dimension: %d\n', size(OutputMin, 1));
fprintf(fid, 'Input_min:\n');
for i = 1:size(inputMin, 1)
    fprintf(fid, '%.4f\n', inputMin(i, 1));
end
fprintf(fid, 'Input_range:\n');
for i = 1:size(inputMin, 1)
    fprintf(fid, '%.4f\n', inputRange(i, 1));
end


fclose(fid);
